language: php

dist: trusty

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - DB=MYSQL
    - COMPOSER_ROOT_VERSION=1.2.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - TRAVIS_NODE_VERSION="6"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1 PDO=1
    - php: 7.1
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1

before_script:
# Extra $PATH
  - export PATH=/usr/lib/chromium-browser/:$PATH

# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer
  - composer validate
  - composer require --prefer-dist --no-update silverstripe/recipe-testing:^1 silverstripe/recipe-cms:4.2.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --prefer-dist --no-update silverstripe/postgresql:2.1.x-dev; fi
  - if [[ $DB == SQLITE ]]; then composer require --prefer-dist --no-update silverstripe/sqlite3:2.0.x-dev; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
