---
Name: swiftypesearch
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Marcz\Swiftype\SwiftypeAdminExtension

Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Swiftype\Extensions\Exporter