---
Name: elasticsearch
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Marcz\Elastic\ElasticAdminExtension

Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Elastic\Extensions\Exporter